### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by Bevinsky** [cashto/resistance#32]
Hi.

I was wondering what license this code is licensed with. As an absence of license implies that all rights to the code are retained by the original author, I was wondering if this was simply an oversight or if it was intentional, as it has consequences when doing further development.

Thanks.

**Comment by cashto** [comment]
Per the packages.json file, this code is licensed under the JSON license (http://www.json.org/license.html). You are free under this license to pretty much do whatever you like with the code, so long as it used for good, and not for evil. 

I'm aware that this limitation is generally considered to be horribly vague to be useful from a legal point of view (http://tanguy.ortolo.eu/blog/article46/json-license), and companies have been known to avoid software released under the JSON license for fear they are opening themselves up to unknown liability and that some court could possibly rule them (or their sub-licensees) to be infringing of such an ambiguous and ill-defined stipulation.  Which is exactly why I chose it, of course.  No one with a stick that far up their ass has any business touching code I wrote for fun.

But seriously, feel free to fork it, spin up your own website, use it as reference in a commercial product, I don't care, anything you like short of somehow using it as a training material on waterboarding prisoners at GTMO to figure out if they are spies or resistance.

**Comment by cashto** [comment]
But also, I am completely open to negotiating a special license for any party who may want to use the code for evil, or who is concerned that *their* customers, partners, or minions might want to use the Software for evil.

**Comment by bignose-debian** [comment]
> I am completely open to negotiating a special license for any party who may want to use the code for evil, or who is concerned that their customers, partners, or minions might want to use the Software for evil.

Hi! This is an explicit request for a license that meets that description. What would you need from us to grant such a license in this work?

**Comment by cashto** [comment]
https://www.youtube.com/watch?v=l91ISfcuzDw

Please be advised that such a license would only release you from any claims of copyright infringement or theft of intellectual property of the protected materials.  Such a license would not indemnify you for any civil or criminal penalties that arise as a consequence of evil, illegal, or tortious use of the materials .  No guarantees or warranties would be conveyed through the granting of such a license.  You would still be liable for any laws broken in your local jurisdiction.

**Comment by bignose-debian** [comment]
> Please be advised that such a license would only release you from any claims of copyright infringement or theft of intellectual property of the protected materials.

Yes, that's well worth pointing out, thank you: a copyright license does nothing to permit actions against third parties. It can only license the recipient to (some set of) actions that copyright law typically restricts to the copyright holder of the work.

I'm seeking from you a license (explicitly granted in text, to any recipient of the ‘resistance’ work, that I can present to anyone as unambiguous license from the copyright holder) that licenses the recipient to do those actions whether or not anyone might consider the action evil.

The closest equivalent text would AFAICT be the terms of [the Expat license](http://www.jclark.com/xml/copying.txt), though you might prefer [the Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0). Either of those would free the work without the problems discussed in this issue. Do either of those work for you?

**Comment by cashto** [comment]
My price for such a license for the original Resistance source code is
$1,000,000.  I don't think a lesser amount of blood money would properly
assuage my feelings of guilt of being complicit in someone else's evil
schemes.

That would be a license for any sort of evil purpose whatsoever.  If you
had a more specific evil purpose in mind, we could discuss a more limited
license that covers that specific scenario.

**Comment by bignose-debian** [comment]
> My price for such a license for the original Resistance source code is $1,000,000. I don't think a lesser amount of blood money would properly assuage my feelings of guilt of being complicit in someone else's evil schemes. 

We know that's not true, because you have granted free-software license in other works.

One thing I'd like for this work is to make it part of the Debian operating system, which would require license under free software terms. Is that something you would like for this work?

I'm not seeking more than the license granted in, for example, https://github.com/cashto/icfp2016 which is free software under the MIT license. Will you grant that license also in this work?

**Comment by cashto** [comment]
Good point.  It's true, I actually don't care what you do with any of my
source code.  Really I chose that license because it's a meme and I enjoy
arguing with random people on the internet about software licences.  It was
a total oversight on my part not to do the same for the ICFP projects.
Thank you for bringing that to my attention, I won't be making the same
mistake going forward.

In the meantime I think a million dollars would be just compensation for my
future inability to have this debate again in the future with someone else
for this project.

**Comment by cashto** [comment]
I'm not sure how making this project part of the Debian distribution would
be valuable to Debian, to you, or even to me.  The Resistance Plus guys
forked this a long time ago and have added so much to it, I don't know the
full extent of where it's gone now, all I know is that they're not using it
for evil.  I really don't see why would care about my crappy early version.

**Comment by AndrewSav** [comment]
Resistance Plus is whole one commit ahead....

**Comment by cashto** [comment]
It's a huge commit.  They probably have stuff they haven't pushed either.

**Comment by bignose-debian** [comment]
(@AndrewSav, that single commit seems to be a huge undifferentiated dump of everything they changed, which as @cashto says, is a lot.)

@cashto, if I understand correctly, you want everyone to be free to build on this work without restriction, and without needing to come to you asking for a license. Is that a fair summary?

If that's so, I can give an answer to this:

> I really don't see why would care about my crappy early version.

We need to care, because the later works derived from this one still require license from you. If we want to build on it with software freedom, that means avoiding the current license conditions and seeking an actually known-to-be-free license.

Yes, if we want to use the work of others (such as The Resistance Plus) we'll need to also ask them. That part would not need to involve you, once we have free-software license from you as sole copyright holder in the earlier work.

You can grant a free license once, by an explicit text in this code base, and then everyone gets it (including those who built on the work before today!) without needing to ask you again. Does that make sense?

**Comment by cashto** [comment]
I would also prefer them to use the work for good and not for evil.

Given the choice between this and not having them use the work at all, I
choose the former.

I still remain mystified how incorporating this specific project into a
Debian distribution would benefit you, me, or the Debian community as a
whole.  I am not aware of much demand for abandoned, unsupported, and
crappily written Resistance implementations.
